linters:
  disable:
    - errcheck
    - govet
    - staticcheck
    - unused
  enable:
    - errorlint
    - gci
    - gofmt
    - gofumpt
    - goimports
    - gosimple
    - misspell
    - revive
    - unconvert
issues:
  max-same-issues: 0
  exclude-rules:
    - linters:
        - revive
      text:  "unexported-return"
