linters:
  disable:
    - errcheck
    - govet
    - staticcheck
    - unused
  enable:
    - errorlint
    - gci
    - gofmt
    - gofumpt
    - gosimple
    - unconvert
issues:
  max-same-issues: 0
